import { serviceIllustrationById } from '@/shared/assets/illustrations';

export const services = [
  {
    id: 'personal',
    title: 'Индивидуальные тренировки',
    onceLabel: '1 тренировка',
    oncePrice: '3000 ₽',
    packLabel: 'Абонемент (5 тренировок)',
    packPrice: '12500 ₽',
    image: serviceIllustrationById.personal,
  },
  {
    id: 'group',
    title: 'Взрослая групповая тренировка',
    onceLabel: '1 занятие (1 час)',
    oncePrice: '1500 ₽',
    packLabel: 'Абонемент (8 занятий)',
    packPrice: '9500 ₽',
    image: serviceIllustrationById.group,
    imageOffsetClassName: 'top-[3.5rem]',
  },
  {
    id: 'child-group',
    title: 'Детская групповая тренировка',
    onceLabel: '1 занятие (1 час)',
    oncePrice: '1000 ₽',
    packLabel: 'Абонемент (8 занятий в месяц)',
    packPrice: '6500 ₽',
    image: serviceIllustrationById.childGroup,
    imageOffsetClassName: 'top-[2.5rem]',
  },
  {
    id: 'table',
    title: 'Аренда стола',
    onceLabel: '1 час аренды',
    oncePrice: '1000 ₽',
    packLabel: 'Абонемент (8 часов аренды)',
    packPrice: '6000 ₽',
    image: serviceIllustrationById.table,
    imageOffsetClassName: 'top-[0.5rem]',
  },
  {
    id: 'robot',
    title: 'Аренда робота БКМ',
    onceLabel: '1 час аренды',
    oncePrice: '600 ₽',
    packLabel: 'Абонемент (8 часов аренды)',
    packPrice: '6000 ₽',
    image: serviceIllustrationById.robot,
  },
];
