import { serviceIllustrationById } from '@/shared/assets/illustrations';

export const services = [
  {
    id: 'personal',
    title: 'Индивидуальные тренировки',
    onceLabel: 'Разовая тренировка',
    oncePrice: 'от 3200 ₽/час',
    packLabel: 'Абонемент на 4 занятия',
    packPrice: 'от 12000 ₽/месяц',
    image: serviceIllustrationById.personal,
  },
  {
    id: 'group',
    title: 'Взрослая групповая тренировка',
    onceLabel: 'Разовая тренировка',
    oncePrice: 'от 1500 ₽/1.5 часа',
    packLabel: 'Абонемент на 8 занятий',
    packPrice: 'от 9600 ₽/месяц',
    image: serviceIllustrationById.group,
    imageOffsetClassName: 'top-[3.5rem]',
  },
  {
    id: 'child-group',
    title: 'Детская групповая тренировка',
    onceLabel: 'Разовая тренировка',
    oncePrice: 'от 1000 ₽/час',
    packLabel: 'Абонемент на 8 занятий',
    packPrice: 'от 6500 ₽/месяц',
    image: serviceIllustrationById.childGroup,
    imageOffsetClassName: 'top-[2.5rem]',
  },
  {
    id: 'table',
    title: 'Аренда стола',
    onceLabel: 'Пн-пт 08:00-17:00',
    oncePrice: '700 ₽/час',
    packLabel: 'Пн-пт 17:00-22:00; сб-вс и праздники',
    packPrice: '900 ₽/час',
    image: serviceIllustrationById.table,
    imageOffsetClassName: 'top-[0.5rem]',
  },
  {
    id: 'robot',
    title: 'Аренда стола + робот',
    onceLabel: 'Пн-пт 08:00-17:00',
    oncePrice: '1200 ₽/час',
    packLabel: 'Пн-пт 17:00-22:00; сб-вс весь день',
    packPrice: '1400 ₽/час',
    image: serviceIllustrationById.robot,
  },
];
